sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 851429dyx
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tSk1XopZ6x2nKsPZdrc
    access-key-secret: 3QjK3vEXOs6JZVJkYemEMXqxO5MNC2
    bucket-name: dyx-sky-take-out